app-build:
  image: "trion/ng-cli"
  before_script:
    - npm install
  stage: build
  artifacts:
    paths:
      - dist/
  script: ng build --prod

deploy-production:
  image: "mitelone/firebase-cli"
  stage: deploy
  dependencies:
    - app-build
  script: firebase deploy --non-interactive --token $FIREBASE_TOKEN
  only:
    - master

